#!/usr/bin/env bash
# zorbit-cli/scripts/bootstrap-lib/nginx.sh
# Generate nginx site config for the env's hostname.
# NOTE: actual reload/install requires sudo — this lib writes the config to
# /tmp and tells the operator to move it. bootstrap-env-root.sh picks it up.
# ---------------------------------------------------------------------------

generate_nginx_config() {
  local hostname="$1"; local env_name="$2"; local port_base="$3"; local out_file="$4"
  cat >"${out_file}" <<NGINX
# nginx site config for ${hostname} (${env_name})
# Generated by bootstrap-env.sh on $(date +%Y-%m-%d)
# Move to /etc/nginx/sites-available/${hostname} via bootstrap-env-root.sh.

upstream ${env_name}_console {
    server 127.0.0.1:${port_base};   # zorbit-unified-console
}

upstream ${env_name}_identity {
    server 127.0.0.1:$((port_base + 1));
}

upstream ${env_name}_navigation {
    server 127.0.0.1:$((port_base + 3));
}

server {
    listen 80;
    server_name ${hostname};
    # Redirect HTTP -> HTTPS. Certbot rewrites this block.
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${hostname};

    # TLS — wildcard cert if available, else certbot-provided.
    ssl_certificate     /etc/letsencrypt/live/onezippy.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/onezippy.ai/privkey.pem;

    # Platform API routes — add each service as needed.
    location /api/identity/       { proxy_pass http://${env_name}_identity/api/; }
    location /api/navigation/     { proxy_pass http://${env_name}_navigation/api/; }

    # Unified console (SPA) — catch-all.
    location / {
        proxy_pass http://${env_name}_console;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    access_log /var/log/nginx/${hostname}.access.log;
    error_log  /var/log/nginx/${hostname}.error.log;
}
NGINX
  log_ok "Wrote nginx config to ${out_file}"
}

emit_nginx_install_instructions() {
  local config_file="$1"; local hostname="$2"
  cat <<INST

  NGINX install requires sudo. Run the following as root:

      sudo mv ${config_file} /etc/nginx/sites-available/${hostname}
      sudo ln -sf /etc/nginx/sites-available/${hostname} /etc/nginx/sites-enabled/${hostname}
      sudo nginx -t
      sudo systemctl reload nginx

  If no wildcard cert exists for onezippy.ai:

      sudo certbot --nginx -d ${hostname}

INST
}
